export interface IndicItem {
    href: string,
    text: string,
    api: string,
}

export const ITEMS: IndicItem[] = [
    {
       "href":"https://en.sse.net.cn/indices/ccfinew.jsp",
       "text":"CCFI",
       "api":"https://en.sse.net.cn/GCSPI/gcspi_ca?indexName=ccfi"
    },
    {
       "href":"https://en.sse.net.cn/indices/scfinew.jsp",
       "text":"SCFI",
       "api":"https://en.sse.net.cn/GCSPI/gcspi_ca?indexName=scfi"
    },
    {
       "href":"https://en.sse.net.cn/indices/scfisnew.jsp",
       "text":"SCFIS",
       "api":"https://en.sse.net.cn/GCSPI/gcspi_ca?indexName=scfis"
    },
    {
       "href":"https://en.sse.net.cn/indices/cbfinew.jsp",
       "text":"CBFI",
       "api":"https://en.sse.net.cn/GCSPI/gcspi_ca?indexName=cbfi"
    },
    {
       "href":"https://en.sse.net.cn/indices/cbcfinew.jsp",
       "text":"CBCFI",
       "api":"https://en.sse.net.cn/GCSPI/gcspi_ca?indexName=cbcfi"
    },
    {
       "href":"https://en.sse.net.cn/indices/cbofinew.jsp",
       "text":"CBOFI",
       "api":"https://en.sse.net.cn/GCSPI/gcspi_ca?indexName=cbofi"
    },
    {
       "href":"https://en.sse.net.cn/indices/cbgfinew.jsp",
       "text":"CBGFI",
       "api":"https://en.sse.net.cn/GCSPI/gcspi_ca?indexName=cbgfi"
    },
    {
       "href":"https://en.sse.net.cn/indices/cdfinew2.jsp",
       "text":"CDFI",
       "api":"https://en.sse.net.cn/GCSPI/gcspi_ca?indexName=cdfi"
    },
    {
       "href":"https://en.sse.net.cn/indices/fdinew2.jsp",
       "text":"FDI",
       "api":"https://en.sse.net.cn/GCSPI/gcspi_ca?indexName=fdi"
    },
    {
       "href":"https://en.sse.net.cn/indices/ctfinew2.jsp",
       "text":"CTFI",
       "api":"https://en.sse.net.cn/GCSPI/gcspi_ca?indexName=ctfi"
    },
    {
       "href":"https://en.sse.net.cn/indices/csinew.jsp",
       "text":"CSI",
       "api":"https://en.sse.net.cn/GCSPI/gcspi_ca?indexName=csi"
    },
    {
       "href":"https://en.sse.net.cn/indices/cicfinew2.jsp",
       "text":"CICFI",
       "api":"https://en.sse.net.cn/GCSPI/gcspi_ca?indexName=cicfi"
    },
    {
       "href":"https://en.sse.net.cn/indices/seafinew2.jsp",
       "text":"SEAFI",
       "api":"https://en.sse.net.cn/GCSPI/gcspi_ca?indexName=seafi"
    },
    {
       "href":"https://en.sse.net.cn/indices/srftinew2.jsp",
       "text":"SRFTI",
       "api":"https://en.sse.net.cn/GCSPI/gcspi_ca?indexName=srfti"
    },
    {
       "href":"https://en.sse.net.cn/indices/brstinew2.jsp",
       "text":"BRSTI",
       "api":"https://en.sse.net.cn/GCSPI/gcspi_ca?indexName=brsti"
    },
    {
       "href":"https://en.sse.net.cn/indices/brtvinew2.jsp",
       "text":"BRTVI",
       "api":"https://en.sse.net.cn/GCSPI/gcspi_ca?indexName=brtvi"
    },
    {
       "href":"https://en.sse.net.cn/indices/brcvinew2.jsp",
       "text":"BRCVI",
       "api":"https://en.sse.net.cn/GCSPI/gcspi_ca?indexName=brcvi"
    },
    {
       "href":"https://en.sse.net.cn/indices/srfinew2.jsp",
       "text":"SRFI",
       "api":"https://en.sse.net.cn/GCSPI/gcspi_ca?indexName=srfi"
    },
    {
       "href":"https://en.sse.net.cn/indices/gcspi_main.jsp",
       "text":"GCSPI",
       "api":"https://en.sse.net.cn/GCSPI/gcspi_ca?indexName=gcspi"
    },
    {
       "href":"https://en.sse.net.cn/indices/gcspi_main.jsp",
       "text":"MTSR",
       "api":"https://en.sse.net.cn/GCSPI/gcspi_ca?indexName=mtsr"
    },
    {
       "href":"https://en.sse.net.cn/indices/gcspi_ca.jsp",
       "text":"CASR",
       "api":"https://en.sse.net.cn/GCSPI/gcspi_ca?indexName=casr"
    },
    {
       "href":"https://en.sse.net.cn/indices/gcspi_port.jsp",
       "text":"PCSR",
       "api":"https://en.sse.net.cn/GCSPI/gcspi_ca?indexName=pcsr"
    },
    {
       "href":"https://en.sse.net.cn/indices/twfi.jsp",
       "text":"TWFI",
       "api":"https://en.sse.net.cn/GCSPI/gcspi_ca?indexName=twfi"
    },
    {
       "href":"https://en.sse.net.cn/indices/ccri.jsp",
       "text":"CCRI",
       "api":"https://en.sse.net.cn/GCSPI/gcspi_ca?indexName=ccri"
    },
 ];